apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
  namespace: crawler
  labels:
    app: synergychat-crawler
data:
  CRAWLER_PORT: "8080"
  CRAWLER_PORT_2: "8081"
  CRAWLER_PORT_3: "8082"
  CRAWLER_KEYWORDS: love,hate,joy,sadness,anger,disgust,fear,surprise
  CRAWELER_DB_PATH: /cache/db